version: 2

jobs:
  build:
    docker:
      - image: adoptopenjdk/openjdk12:jdk-12.0.1_12-slim

    working_directory: /work

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: show/resolve dependency
          command: ./gradlew dependencies
      - run:
          name: build application
          command: ./gradlew installDist
      - run:
          name: run benchmark
          command: build/install/jmh-java-collection-benchmark/bin/jmh-java-collection-benchmark >> build/result.txt
          
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - store_artifacts:
          path: ./build/result.txt
