version: 2

jobs:
  build:
    docker:
      - image: mikeneck/jmh-jdk12-aws

    working_directory: /jmh-java-collection-benchmark

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: show/resolve dependency
          command: ./gradlew dependencies
      - run:
          name: build application
          command: ./gradlew distZip
      - run:
          name: put object
          command: aws s3api put-object --bucket org.mikeneck.test --key jmh-java-collection-benchmark.zip --body build/distributions/jmh-java-collection-benchmark.zip
          
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - store_artifacts:
          path: ./build/distributions/jmh-java-collection-benchmark.zip
